### ISSUE TITLE
roadmap needs to be updated

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/opendevstack.github.io#134] opened 2020-02-27 11:50 UTC
Homepage http://www.opendevstack.org/ currently displays the following roadmap information:

- June 2019 - release 1.1
- October 2019 - release 2.0
- Following: Release of continuously advanced versions

While 2.0 is already released (but with different date), the 3.0 Release is in work.

**Comment by michaelsauter** [comment] 2020-02-27 13:02
Duplicate of #115

**Closed as completed by michaelsauter** 2020-02-27 13:02 UTC
